#!/bin/bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"
# shellcheck source=lib/metadata.bash
. "$DIR/../lib/metadata.bash"


commands=()

[[ -n "$(plugin_read_list RUN)" ]] && commands+=("RUN")
[[ -n "$(plugin_read_list WRAP_COMMAND)" ]] && commands+=("WRAP_COMMAND")

if ! in_array "RUN" "${commands[@]}" && ! in_array "WRAP_COMMAND" "${commands[@]}" ; then
  exit 0
fi

run_service="$(plugin_read_config RUN)"
override_file="docker-compose.buildkite-${BUILDKITE_BUILD_NUMBER}-override.yml"
prebuilt_candidates=()

[[ -n "${run_service}" ]] && prebuilt_candidates+=("$run_service")

# Build a list of services that need to be pulled down
while read -r name ; do
  if [[ -n "$name" ]] ; then
    if ! in_array "$name" "${prebuilt_candidates[@]}" ; then
      prebuilt_candidates+=("$name")
    fi
  fi
done <<< "$(plugin_read_list PULL)"

# A list of tuples of [service image cache_from] for build_image_override_file
prebuilt_service_overrides=()
prebuilt_services=()

# We look for a prebuilt images for all the pull services and the run_service.
for service_name in "${prebuilt_candidates[@]}" ; do
  if prebuilt_image=$(get_prebuilt_image "$service_name") ; then
    echo "~~~ :docker: Found a pre-built image for $service_name"
    prebuilt_service_overrides+=("$service_name" "$prebuilt_image" "")
    prebuilt_services+=("$service_name")
  fi
done

# If there are any prebuilts, we need to generate an override docker-compose file
if [[ ${#prebuilt_services[@]} -gt 0 ]] ; then
  echo "~~~ :docker: Creating docker-compose override file for prebuilt services"
  build_image_override_file "${prebuilt_service_overrides[@]}" | tee "$override_file"
fi

# Export config values
compose_config=()
for file in $(docker_compose_config_files) ; do
  compose_config+=("$file")
done
test -f "$override_file" && compose_config+=("${override_file}")
echo "Setting DOCKER_COMPOSE_CONFIG_FILES=${compose_config[@]}"
export DOCKER_COMPOSE_CONFIG_FILES="${compose_config[@]}"
echo "Setting DOCKER_COMPOSE_PROJECT_NAME=$(docker_compose_project_name)"
export DOCKER_COMPOSE_PROJECT_NAME="$(docker_compose_project_name)"
echo "Setting DOCKER_COMPOSE_CONTAINER_PREFIX=$(docker_compose_project_name)_build_${BUILDKITE_BUILD_NUMBER}"
export DOCKER_COMPOSE_CONTAINER_PREFIX="$(docker_compose_project_name)_build_${BUILDKITE_BUILD_NUMBER}"
